server:
  port: 7072
dubbo:
  application:
    name: ba-usercore-consumer
  protocol:
    name: dubbo   # 常用协议：dubbo、http、webService等
    port: 20881   # 发布dubbo端口号为20880
  registry:
    address: zookeeper://localhost:2181   # dubbo注册中心地址  zookeeper地址
    client: curator